name: Deploy Next.js site to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Detect package manager
      - name: Detect package manager
        id: detect-package-manager
        run: |
          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_OUTPUT
          elif [ -f "${{ github.workspace }}/package-lock.json" ]; then
            echo "manager=npm" >> $GITHUB_OUTPUT
          else
            echo "Unable to determine package manager"
            exit 1
          fi

      # 3. Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: ${{ steps.detect-package-manager.outputs.manager }}

      # 4. Restore Next.js cache
      - name: Restore Next.js cache
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-

      # 5. Install dependencies
      - name: Install dependencies
        run: |
          if [ "${{ steps.detect-package-manager.outputs.manager }}" == "yarn" ]; then
            yarn install --frozen-lockfile
          else
            npm ci
          fi

      # 6. Build the Next.js site
      - name: Build Next.js
        run: |
          if [ "${{ steps.detect-package-manager.outputs.manager }}" == "yarn" ]; then
            yarn next build
          else
            npx --no-install next build
          fi

      # 7. Export static HTML
      - name: Export Next.js
        run: |
          if [ "${{ steps.detect-package-manager.outputs.manager }}" == "yarn" ]; then
            yarn next export
          else
            npx --no-install next export
          fi

      # 8. Upload artifact for GitHub Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Show deployed URL
        run: echo "Your site is live at ${{ steps.deployment.outputs.page_url }}"
