name: Deploy Next.js 15 site to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Build Next.js
      - name: Build Next.js
        run: npx --no-install next build

      # 5. Export static HTML
      - name: Export static HTML
        run: npx --no-install next export

      # 6. Configure GitHub Pages
      - name: Configure Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next

      # 7. Upload artifact (must point to 'out/')
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

      # 8. Deploy to GitHub Pages
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4

      # 9. Show deployed URL
      - name: Deployment URL
        run: echo "Your site is live at ${{ steps.deployment.outputs.page_url }}"
