name: Deploy Next.js 15 to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Build Next.js
      - name: Build Next.js
        run: npx next build

      # 5. Export static HTML
      - name: Export Next.js static HTML
        run: npx next export

      # 6. Configure GitHub Pages
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next

      # 7. Upload Pages artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Next 15 outputs static HTML to 'out' folder
          path: out

      # 8. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      # 9. Output deployment URL
      - name: Deployment URL
        run: echo "Your site is live at ${{ steps.deployment.outputs.page_url }}"
